[package]
name = "bpftop"
version = "0.4.0"
edition = "2021"

[dependencies]
libbpf-rs = "0.22.1"
libbpf-sys = "1.3.0"
crossterm = "0.27.0"
anyhow = "1.0.81"
ratatui = { version = "0.26.1", default-features = false, features = ['crossterm'] }
nix = { version = "0.28.0", features = ["user"] }
circular-buffer = "0.1.7"
procfs = "0.16.0"
tui-input = "0.8.0"
