[package]
name = "bpftop"
version = "0.4.2"
edition = "2021"

[build-dependencies]
libbpf-cargo = "0.23.0"

[dependencies]
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-journald = "0.3.0"
libbpf-rs = "0.23.0"
libbpf-sys = "1.4.1"
crossterm = "0.27.0"
anyhow = "1.0.83"
ratatui = { version = "0.26.2", default-features = false, features = ['crossterm'] }
nix = { version = "0.28.0", features = ["user"] }
circular-buffer = "0.1.7"
procfs = "0.16.0"
tui-input = "0.8.0"
